// Generated by gencpp from file myRosPackage/AddTwoIntsCopy.msg
// DO NOT EDIT!


#ifndef MYROSPACKAGE_MESSAGE_ADDTWOINTSCOPY_H
#define MYROSPACKAGE_MESSAGE_ADDTWOINTSCOPY_H

#include <ros/service_traits.h>


#include <myRosPackage/AddTwoIntsCopyRequest.h>
#include <myRosPackage/AddTwoIntsCopyResponse.h>


namespace myRosPackage
{

struct AddTwoIntsCopy
{

typedef AddTwoIntsCopyRequest Request;
typedef AddTwoIntsCopyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoIntsCopy
} // namespace myRosPackage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myRosPackage::AddTwoIntsCopy > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::myRosPackage::AddTwoIntsCopy&) { return value(); }
};

template<>
struct DataType< ::myRosPackage::AddTwoIntsCopy > {
  static const char* value()
  {
    return "myRosPackage/AddTwoIntsCopy";
  }

  static const char* value(const ::myRosPackage::AddTwoIntsCopy&) { return value(); }
};


// service_traits::MD5Sum< ::myRosPackage::AddTwoIntsCopyRequest> should match 
// service_traits::MD5Sum< ::myRosPackage::AddTwoIntsCopy > 
template<>
struct MD5Sum< ::myRosPackage::AddTwoIntsCopyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myRosPackage::AddTwoIntsCopy >::value();
  }
  static const char* value(const ::myRosPackage::AddTwoIntsCopyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myRosPackage::AddTwoIntsCopyRequest> should match 
// service_traits::DataType< ::myRosPackage::AddTwoIntsCopy > 
template<>
struct DataType< ::myRosPackage::AddTwoIntsCopyRequest>
{
  static const char* value()
  {
    return DataType< ::myRosPackage::AddTwoIntsCopy >::value();
  }
  static const char* value(const ::myRosPackage::AddTwoIntsCopyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myRosPackage::AddTwoIntsCopyResponse> should match 
// service_traits::MD5Sum< ::myRosPackage::AddTwoIntsCopy > 
template<>
struct MD5Sum< ::myRosPackage::AddTwoIntsCopyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myRosPackage::AddTwoIntsCopy >::value();
  }
  static const char* value(const ::myRosPackage::AddTwoIntsCopyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myRosPackage::AddTwoIntsCopyResponse> should match 
// service_traits::DataType< ::myRosPackage::AddTwoIntsCopy > 
template<>
struct DataType< ::myRosPackage::AddTwoIntsCopyResponse>
{
  static const char* value()
  {
    return DataType< ::myRosPackage::AddTwoIntsCopy >::value();
  }
  static const char* value(const ::myRosPackage::AddTwoIntsCopyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYROSPACKAGE_MESSAGE_ADDTWOINTSCOPY_H
