// Generated by gencpp from file myRosPackage/myMSG.msg
// DO NOT EDIT!


#ifndef MYROSPACKAGE_MESSAGE_MYMSG_H
#define MYROSPACKAGE_MESSAGE_MYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myRosPackage
{
template <class ContainerAllocator>
struct myMSG_
{
  typedef myMSG_<ContainerAllocator> Type;

  myMSG_()
    {
    }
  myMSG_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::myRosPackage::myMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myRosPackage::myMSG_<ContainerAllocator> const> ConstPtr;

}; // struct myMSG_

typedef ::myRosPackage::myMSG_<std::allocator<void> > myMSG;

typedef boost::shared_ptr< ::myRosPackage::myMSG > myMSGPtr;
typedef boost::shared_ptr< ::myRosPackage::myMSG const> myMSGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myRosPackage::myMSG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myRosPackage::myMSG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myRosPackage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'myRosPackage': ['/home/alex/Desktop/ROS_tutorials/src/myRosPackage/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myRosPackage::myMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myRosPackage::myMSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myRosPackage::myMSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myRosPackage::myMSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myRosPackage::myMSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myRosPackage::myMSG_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myRosPackage::myMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::myRosPackage::myMSG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::myRosPackage::myMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myRosPackage/myMSG";
  }

  static const char* value(const ::myRosPackage::myMSG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myRosPackage::myMSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::myRosPackage::myMSG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myRosPackage::myMSG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myMSG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myRosPackage::myMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::myRosPackage::myMSG_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MYROSPACKAGE_MESSAGE_MYMSG_H
